---
name: "Container Size Diff"
description: "Creates a Markdown summary of the size differences between two containers"

inputs:
  from-container:
    description: "Baseline container image for size comparison"
    required: true
  to-container:
    description: "Container image to be compared to the baseline"
    required: true

outputs:
  size-diff-markdown:
    description: "Markdown formatted output of container size comparison"
    value: ${{ steps.size-diff.outputs.markdown }}

runs:
  using: "composite"
  steps:
    - run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - run: |
        MARKDOWN="$(container-size-diff.sh ${INPUT_FROM_CONTAINER} ${INPUT_TO_CONTAINER})"
        MARKDOWN="${MARKDOWN//'%'/'%25'}"
        MARKDOWN="${MARKDOWN//$'\n'/'%0A'}"
        MARKDOWN="${MARKDOWN//$'\r'/'%0D'}"

        echo "markdown=${MARKDOWN}" >> "$GITHUB_OUTPUT"
      id: size-diff
      shell: bash
      env:
        INPUT_FROM_CONTAINER: ${{ inputs.from-container }}
        INPUT_TO_CONTAINER: ${{ inputs.to-container }}
