ENABLE:
  - ACTION
  - DOCKERFILE
  - GHERKIN
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - YAML
DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - JSON_JSONLINT
  - SPELL_CSPELL
SARIF_REPORTER: true
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
SPELL_LYCHEE_FILE_EXTENSIONS:
  [".feature", ".json", ".md", ".md.j2", ".txt", ".yaml", ".yml"]
FILTER_REGEX_EXCLUDE: (CHANGELOG.md|package-lock.json)
# tasks.json is wrongfully matched against another schema,
# and schemas for .vscode/[tasks.json|launch.json] are built
# dynamically based upon context (e.g. installed extensions)
# hence the exclusion
JSON_V8R_FILTER_REGEX_EXCLUDE: (\.vscode)
REPOSITORY_TRIVY_ARGUMENTS: --ignorefile .github/linters/.trivyignore.yml
