ENABLE:
  - ACTION
  - DOCKERFILE
  - GHERKIN
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - YAML
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - JSON_JSONLINT
  - SPELL_CSPELL
SARIF_REPORTER: true
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
FILTER_REGEX_EXCLUDE: (CHANGELOG.md)
# tasks.json is wrongfully matched against another schema,
# and schemas for .vscode/[tasks.json|launch.json] are built
# dynamically based upon context (e.g. installed extensions)
# hence the exclusion
JSON_V8R_FILTER_REGEX_EXCLUDE: (\.vscode)
