ENABLE:
  - ACTION
  - DOCKERFILE
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - YAML
DISABLE_LINTERS:
  - MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - JSON_JSONLINT
  - SPELL_CSPELL
SARIF_REPORTER: true
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
FILTER_REGEX_EXCLUDE: (CHANGELOG.md)
