ENABLE:
  - ACTION
  - DOCKERFILE
  - GHERKIN
  - JSON
  - MARKDOWN
  - REPOSITORY
  - SPELL
  - YAML
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_DEVSKIM
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_KICS
  - REPOSITORY_SEMGREP
  - JSON_JSONLINT
  - SPELL_CSPELL
SARIF_REPORTER: true
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
FILTER_REGEX_EXCLUDE: (CHANGELOG.md|package-lock.json)
# tasks.json is wrongfully matched against another schema,
# and schemas for .vscode/[tasks.json|launch.json] are built
# dynamically based upon context (e.g. installed extensions)
# hence the exclusion
JSON_V8R_FILTER_REGEX_EXCLUDE: (\.vscode)
REPOSITORY_TRIVY_ARGUMENTS: --ignorefile .github/linters/.trivyignore.yml
# Temporarily disable hadolint errors as version v2.13.1
# (https://github.com/hadolint/hadolint/issues/985) is
# not yet part of megalinter
DOCKERFILE_HADOLINT_DISABLE_ERRORS: true
