---
name: Acceptance Test

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      # Create a GitHub Codespace and communicate the image version via a Codespace secret (should be a Codespace environment variable).
      # This secret is used by devcontainer.json, as such it is a resource that should not be used concurrently.
      - name: Start Codespace
        run: |
          set -Eeuo pipefail
          gh secret set -a codespaces IMAGE_VERSION --body "pr-${{ github.event.pull_request.number }}"
          echo CODESPACE_NAME="$(gh codespace create -R "${{ github.repository }}" -b "$HEAD_REF" -m basicLinux32gb --devcontainer-path ".devcontainer/${{ inputs.flavor }}-test/devcontainer.json" --idle-timeout 10m --retention-period 1h)" >> "$GITHUB_ENV"
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Wait for Codespace to be active
        run: |
          set -Eeuo pipefail

          MAX_WAIT_SECONDS=$((3 * 60))
          SECONDS_ELAPSED=0

          while true; do
            STATE=$(gh codespace list --json name,state --jq ".[] | select(.name == \"$CODESPACE_NAME\") | .state")
            echo "Current state: $STATE"
            if [ "$STATE" == "Available" ]; then
              echo "Codespace is active!"
              break
            fi
            if [ $SECONDS_ELAPSED -ge $MAX_WAIT_SECONDS ]; then
              echo "Timeout reached. Codespace is not active."
              exit 1
            fi
            sleep 5
            SECONDS_ELAPSED=$((SECONDS_ELAPSED + 5))
          done
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
      - run: cd test/${{ inputs.flavor }}/features && npm test
        env:
          GITHUB_USER: ${{ secrets.TEST_GITHUB_USER }}
          GITHUB_PASSWORD: ${{ secrets.TEST_GITHUB_PASSWORD }}
          GITHUB_TOTP_SECRET: ${{ secrets.TEST_GITHUB_TOTP_SECRET }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: playwright-artifacts
          path: |
            test-results/
          retention-days: 10
      - run: |
          set -Eeuo pipefail
          gh codespace delete --force --codespace "$CODESPACE_NAME"
          gh secret set -a codespaces IMAGE_VERSION --body "latest"
        if: always()
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
