---
name: Acceptance Test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [cpp]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18
      #- run: npm ci
      #- run: npx playwright install --with-deps
      - run: |
          gh codespace create -R ${{ github.repository }} -b $HEAD_REF -m basicLinux32gb --devcontainer-path .devcontainer/${{ matrix.flavor }}-test/devcontainer.json
        env:
          HEAD_REF: ${{ github.head_ref }}
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          IMAGE_VERSION: pr-${{ github.event.pull_request.number }}
      - run: cd .devcontainer/${{ matrix.flavor }}/e2e && npm test
        env:
          GITHUB_USER: ${{ secrets.TEST_GITHUB_USER }}
          GITHUB_PASSWORD: ${{ secrets.TEST_GITHUB_PASSWORD }}
          GITHUB_TOTP_SECRET: ${{ secrets.TEST_GITHUB_TOTP_SECRET }}
