---
name: Cleanup Images

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

permissions: {}

jobs:
  cleanup-images:
    name: 🧹 Clean Images
    runs-on: ubuntu-latest
    permissions:
      packages: write # is needed by dataaxiom/ghcr-cleanup-action to delete untagged and orphaned images
    steps:
      - uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
      - uses: dataaxiom/ghcr-cleanup-action@34a2b6c814b9c6bcb92f78cba3e56a7ab9ca7a86 # v1.1.0
        with:
          delete-orphaned-images: true
          delete-untagged: true
          packages: amp-devcontainer,amp-devcontainer-cpp,amp-devcontainer-rust
