---
name: Cleanup Images

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

permissions: {}

jobs:
  cleanup-images:
    name: 🧹 Clean Images
    runs-on: ubuntu-latest
    permissions:
      packages: write # is needed by dataaxiom/ghcr-cleanup-action to delete untagged and orphaned images
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1.2.0
        with:
          delete-orphaned-images: true
          delete-untagged: true
          packages: amp-devcontainer,amp-devcontainer-cpp,amp-devcontainer-rust
