---
name: Integration Test

on:
  workflow_call:
    inputs:
      container:
        required: true
        type: string
      flavor:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        runner: ["ubuntu-latest", "ubuntu-24.04-arm"]
    runs-on: ${{ matrix.runner }}
    container: ${{ inputs.container }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: inputs.flavor == 'cpp'
        with:
          path: test/.xwin-cache
          key: xwin-cache
          restore-keys: |
            xwin-cache
      - run: bats --formatter junit test/${{ inputs.flavor }}/integration-tests.bats | tee test-report-${{ inputs.flavor }}-${{ matrix.runner }}.xml
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: test-results-${{ inputs.flavor }}-${{ matrix.runner }}
          path: test-report-*.xml
