---
name: Close Stale Issues & Pull Requests

on:
  schedule:
    - cron: "30 1 * * *"

permissions: {}

jobs:
  close-issues:
    name: ♻️ Close Stale Issues & PRs
    runs-on: ubuntu-latest
    permissions:
      issues: write # is needed by actions/stale to close/comment on issues
      pull-requests: write # is needed by actions/stale to close/comment on PRs
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          stale-issue-message: "This issue is marked stale because it has been open for an extended period with no activity. Remove the 'stale' label or comment otherwise this issue will be closed in 7 days."
          stale-pr-message: "This pull request is marked stale because it has been open for an extended period with no activity. Remove the 'stale' label or comment otherwise this pull request will be closed in 7 days."
          exempt-all-milestones: true
