---
name: Linting & Formatting

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    # Run on push to main, this is not actionable
    # but it gives us a baseline for PRs
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  linter:
    name: 🧹 Lint & Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # is needed by zizmorcore/zizmor-action
      pull-requests: write # is needed by oxsecurity/megalinter and reviewdog/action-suggester to post PR comments
      security-events: write # is needed by oxsecurity/megalinter for uploading sarif files
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          persona: pedantic
      # flavors/dotnet is the smallest flavor of MegaLinter that contains the linters
      # we are interested in.
      - uses: oxsecurity/megalinter/flavors/dotnet@ef3e84b8b836d76db562d0f3ed7da61e8fd538bc # v9.6.0
        env:
          APPLY_FIXES: all
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        if: success() || failure()
        with:
          sarif_file: megalinter-reports/megalinter-report.sarif
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: success() || failure()
        with:
          name: Linter Report
          path: |
            megalinter-reports
      - uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
        with:
          tool_name: MegaLinter
