---
name: Supply-chain Security

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: "16 19 * * 6"
  push:
    branches: [main]

permissions: {}

jobs:
  ossf-scorecard:
    name: 🛡️ OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # is needed by github/codeql-action/upload-sarif to upload sarif files
      id-token: write # is needed by ossf/scorecard-action to authenticate with OIDC
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true
      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: results.sarif
