---
name: Supply-chain Security

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: "16 19 * * 6"
  push:
    branches: [main]

permissions: {}

jobs:
  ossf-scorecard:
    name: 🛡️ OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # is needed by github/codeql-action/upload-sarif to upload sarif files
      id-token: write # is needed by ossf/scorecard-action to authenticate with OIDC
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true
      - uses: github/codeql-action/upload-sarif@0d579ffd059c29b07949a3cce3983f0780820c98 # v4.32.6
        with:
          sarif_file: results.sarif
