---
name: Cleanup Pull Request Images

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  delete-images:
    name: 🗑️ Delete PR Images
    runs-on: ubuntu-latest
    permissions:
      packages: write # is needed by dataaxiom/ghcr-cleanup-action to delete images
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: dataaxiom/ghcr-cleanup-action@374e2028c8fb93b7219f3771cd405fab95d3dec4 # v1.2.0
        with:
          delete-tags: pr-${{ github.event.pull_request.number }}
          packages: amp-devcontainer,amp-devcontainer-cpp,amp-devcontainer-rust

  cleanup-cache:
    name: 🧹 Cleanup Cache
    runs-on: ubuntu-latest
    permissions:
      actions: write # is needed to delete workflow run caches
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - run: |
          gh extension install actions/gh-actions-cache

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          for cacheKey in $(gh actions-cache list -R "${GH_REPO}" -B "${BRANCH}" | cut -f 1)
          do
              gh actions-cache delete "${cacheKey}" -R "${GH_REPO}" -B "${BRANCH}" --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
