---
name: Prime Cache

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  prime-docker-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: ["cpp", "rust"]
    steps:
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2 # v6.0.1
        with:
          file: .devcontainer/${{ matrix.flavor }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ github.repository }}-${{ matrix.flavor }}
          cache-to: type=gha,mode=max,scope=${{ github.repository }}-${{ matrix.flavor }}
  prime-xwin-cache:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -Eeuo pipefail
          mkdir test
          docker run --rm --mount type=bind,src="$(pwd)/test",dst=/ws -w /ws ghcr.io/${{ github.repository }}-cpp:latest xwin --accept-license splat --preserve-ms-arch-notation
      - uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: test/.xwin-cache
          key: xwin-cache
