---
name: Social Interaction

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions: {}

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit
      - uses: actions/first-interaction@34f15e814fe48ac9312ccf29db4e74fa767cbab7 # v1.3.0
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for adding your first issue. We will be looking into it as soon as possible."
          pr-message: "Thanks for your first PR. We really appreciate it!"
