---
name: Validate Pull-Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  conventional-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: Namchee/conventional-pr@8378fb29fcf8e0b18ce4f366ffd70483e5e9e8d8 # v0.15.3
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          body: false
          issue: false
          close: false
