---
name: Build, Push & Test

on:
  workflow_call:
    secrets:
      TEST_GITHUB_TOKEN:
        required: true
      TEST_GITHUB_USER:
        required: true
      TEST_GITHUB_PASSWORD:
        required: true
      TEST_GITHUB_TOTP_SECRET:
        required: true

permissions: {}

jobs:
  build-push:
    strategy:
      matrix:
        flavor: [cpp, rust]
    uses: ./.github/workflows/wc-build-push.yml
    permissions:
      actions: read
      attestations: write
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}
      DOCKER_REGISTRY_PASSWORD: ${{ github.token }}
    with:
      devcontainer-metadata-file: .devcontainer/${{ matrix.flavor }}/devcontainer-metadata.json
      dockerfile: .devcontainer/${{ matrix.flavor }}/Dockerfile
      image-name: ${{ github.repository }}-${{ matrix.flavor }}
      registry: ghcr.io
      runner-labels: ubuntu-latest
      build-test-runner-labels: '["ubuntu-latest", "ubuntu-24.04-arm"]'

  dependency-review:
    needs: build-push
    uses: ./.github/workflows/wc-dependency-review.yml
    permissions:
      contents: read
      pull-requests: write

  integration-test:
    strategy:
      matrix:
        flavor: [cpp, rust]
        runner: ["ubuntu-latest", "ubuntu-24.04-arm"]
    needs: build-push
    uses: ./.github/workflows/wc-integration-test.yml
    permissions:
      contents: read
    with:
      image-name: ${{ github.repository }}-${{ matrix.flavor }}
      test-file: test/${{ matrix.flavor }}/integration-tests.bats
      runner-labels: ${{ matrix.runner }}

  acceptance-test:
    strategy:
      matrix:
        flavor: [cpp]
    needs: build-push
    uses: ./.github/workflows/wc-acceptance-test.yml
    permissions:
      contents: read
    secrets:
      TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
      TEST_GITHUB_USER: ${{ secrets.TEST_GITHUB_USER }}
      TEST_GITHUB_PASSWORD: ${{ secrets.TEST_GITHUB_PASSWORD }}
      TEST_GITHUB_TOTP_SECRET: ${{ secrets.TEST_GITHUB_TOTP_SECRET }}
    with:
      flavor: ${{ matrix.flavor }}

  publish-test-results:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    needs: [acceptance-test, integration-test]
    if: ${{ !cancelled() }}
    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          merge-multiple: true
          pattern: test-results-*
      - uses: EnricoMi/publish-unit-test-result-action@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6 # v2.20.0
        with:
          files: test-report-*.xml

  generate-documents:
    uses: ./.github/workflows/wc-document-generation.yml
    permissions:
      contents: read
