---
name: Dependency Review

on:
  workflow_call:
    inputs:
      runner-labels:
        description: >-
          JSON array used to select the action runner.
          Must be valid JSON.

          Examples:
            '["ubuntu-latest"]'
            '["self-hosted", "linux", "x86_64"]'
        required: false
        type: string
        default: '["ubuntu-latest"]'

permissions: {}

jobs:
  dependency-review:
    name: Review
    runs-on: ${{ fromJson(inputs.runner-labels) }}
    permissions:
      contents: read
      pull-requests: write # is needed by actions/dependency-review-action to write PR summaries
    steps:
      - uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: on-failure
          fail-on-severity: critical
