---
name: Document Generation

on:
  workflow_call:

permissions: {}

jobs:
  generate-documents:
    name: Generate Documents
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: |
          set -Eeuo pipefail
          sudo apt-get update && sudo apt-get install --no-install-recommends -y plantuml
          python -m pip install gherkin-official==38.0.0 sbdl==1.21.3
      - name: Build & Validate SBDL model
        run: |
          set -Eeuo pipefail
          sbdl -m compile test/cpp/features/*.feature > amp-devcontainer.sbdl
      - name: Generate SRS document
        run: |
          set -Eeuo pipefail
          sbdl -m template-fill --template docs/templates/software-requirements-specification.md.j2 amp-devcontainer.sbdl > software-requirements-specification.md
      - uses: docker://pandoc/extra:3.9.0.0-ubuntu@sha256:72afa9c8d3300e5f10c9c4330e101725687f2179bffd912fb859c6d2ae85de62
        with:
          args: --template eisvogel --syntax-highlighting idiomatic --number-sections --output software-requirements-specification.pdf software-requirements-specification.md
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: documents
          path: |
            *.pdf
            *.sbdl
          retention-days: 2
