---
name: Dependency Review

on:
  workflow_call:
    inputs:
      runner-labels:
        description: >-
          JSON array used to select the action runner.
          Must be valid JSON.

          Examples:
            '["ubuntu-latest"]'
            '["self-hosted", "linux", "x86_64"]'
        required: false
        type: string
        default: '["ubuntu-latest"]'

permissions: {}

jobs:
  dependency-review:
    name: Review
    runs-on: ${{ fromJson(inputs.runner-labels) }}
    permissions:
      contents: read
      pull-requests: write # is needed by actions/dependency-review-action to write PR summaries
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo-and-containers: true
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: on-failure
          fail-on-severity: critical
